---
- name: Hello, Ansible Playbook
  hosts: debians
  become: true
  tasks:
    - name: Example from Ansible Playbook
      ansible.builtin.ping:
    - name: Show gateway
      ansible.builtin.debug:
        msg: "{{ ansible_default_ipv4.gateway }}"
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Unzip
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: Install apache
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Start apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
    - name: Install mariadb
      ansible.builtin.apt:
        name: mariadb-server
    - name: Uninstall htop
      ansible.builtin.apt:
        name: htop
        state: absent
    - name: Desplegar aplicacion
      ansible.builtin.unarchive:
        src: /home/tux/Downloads/2048.zip
        dest: /var/www/html/
        owner: root
        group: root
