---
# tasks file for mariadb
- name: Install Fedora Webserver
  import_task: fedora_webserver.yml
  when: ansible_fact['os_family'] == "Fedora"

- name: Install Debian Webserver
  import_task: debian_webserver.yml
  when: ansible_fact['os_family'] == "Debian"
